const ACTION_TYPE = {
  POSTS_RESIVED: "POSTS_RESIVED",
  POSTS_RESIVED_SUCCESSFUL: "POSTS_RESIVED_SUCCESSFUL",
  POSTS_RESIVED_ERROR: "POSTS_RESIVED_ERROR",
  CURRENT_POST_RESIVED: "CURRENT_POST_RESIVED",
  CURRENT_POST_RESIVED_SUCCESSFUL: "CURRENT_POST_RESIVED_SUCCESSFUL",
  CURRENT_POST_RESIVED_ERROR: "CURRENT_POST_RESIVED_ERROR",
  CREATE_POST: "CREATE_POST",
  CREATE_POST_SUCCESSFUL: "CREATE_POST_SUCCESSFUL",
  CREATE_POST_ERROR: "CREATE_POST_ERROR",
}

export default ACTION_TYPE
